language: python
python:
    - "2.6"
    - "2.7"

branches:
  only:
    - master

notifications:
  email:
    - ben@groovie.org
  irc: "irc.mozilla.org#services-dev"

before_install:
    - sudo apt-get -q update >/dev/null 2>&1
    - sudo apt-get -q install libevent-dev libpcre3-dev libzookeeper-dev >/dev/null 2>&1

install:
    - make build
    - ./bin/easy_install -U zc-zookeeper-static

script: make test
